node {
   def commit_id
   environment {
      DOCKERHUB_CREDENTIALS = credentials('dockerhub)
  }
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('build') {
     sh 'docker build -t santhosh1987/nodjs-app-jenkins-pipeline:latest .'
   }
   stage('login') {
     sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS '
   }
   stage('push') {
     sh 'docker push santhosh1987/nodjs-app-jenkins-pipeline:latest'
   }

}
